#+TITLE: Glass Bead Game

* Hesse
pg 21-23 discusses culture and meaning (lack thereof)
- "...the youth and creative period of our culture is over" (pg 24)
- Glass bead game being assimlated and altered between disciplines (32)
- They say [the glass bead game]is a substitue for the arts , and that the players are mere populizers; that they can no longer be regarded as truly devoted to the things of the mind, but are merely artistic dilettantes.." (pg 81)`
  - *Sounds a little like salient links to me*
    - The point of consilience is to further/deepen understanding but its not clear if thats actually whats happening with the game.
  - "...if the anatomist sees nothing but his patterns, and ignores the unique, individual reality of his object, then he is a Castalian, a Glass Bead Player/" (pg 168)
-"our mission is to recognize contraries for what they are: first of all,contraries, but then as opposite poles of unity. Such is the nature of the glass bead game." (81)


* Essay
Though the glass bead game remains opaque in terms of its mechanics, it's to clear to me that it only provides the illusion of consilience, and not the genuine article. The few descriptions of the glass bead game that Hesse did dole out reminded me a lot of what Boyer calls "salient connections." According to Boyer, salient connections are a mode of scholarship that are popular amongst cultural anthropologits sociologists, whereby "people assess new contributions in terms of the connections they establish between facts or ideas..." Compare that to this description of the glass bead game by the novel's narrator: "The Glass Bead Game is thus a mode of playing with the total contents and values of our culture; it plays with them as, say, in the great age of the arts a painter might have played with the colors on his palette. All the insights, noble thoughts, and works of art that the human race has produced in its creative eras, all that subsequent periods of scholarly study have reduced to concepts and converted into intellectual values the Glass Bead Game player plays like the organist on an organ." There are discrepancies in the finer details between Boyer's sailent connections and the glass bead game, but, critically, they are similar in that interdisciplinary connections are highly valued by their practitioners. 

However, the issue with salient connections, as pointed out by Boyer, is that they tend to be merely nonrigorous intellectual exercises with little applicability to individuals outside the discipline, and therefore do not contribute our body of knowledge in any real sense. This is a problem because currently salient connections are the dominant mode of scholarship in a lot of disciplines which Boyer asserts has lead to intellectual stagnation and arrested development. This state of affairs is mirrored strongly in the novel. Indeed, in Castalia glass bead game scholarship is considered the height of intellectualism, with the Magister Ludi seated apically. However, it becomes clear pretty early on that the Castalians, for all their erudition, are incapable of producing 

